## Aprendizaje no supervisado

Recordemos que este es simplemente un repaso de los métodos usados con sickit-learn. No se esta haciendo profundización en los métodos ni nada por el estilo. 

Nota importante de la distinción del aprendizaj supervisado al no supervisado. En el aprendizaj supervisado tenemos una variable objetivo que deseamos CLASIFICAR o predecir con una REGRESIÓN. Con el aprendizaje no supervisado no existe esa variable respuesta la cual me dará un valor o me dirá a donde pertenecen estos datos, el aprendizaje no supervisado encuentra la información instrínseca a los datos, los agrupa, comprime y entiende su naturaleza geométrica. No busca asignar respuestas correctas preexistentes, sino revelar la organización o arquitectura oculta de la información.

In [1]:
import numpy as np

np.random.seed(1)

In [5]:
#
# K-means clustering
#
from sklearn import cluster, datasets # agrupamiento


X_iris, y_iris = datasets.load_iris(return_X_y=True)

# instancia del métood e agrupamiento k-means
# con la cantidad de clusters que se quieren realizar. 
k_means = cluster.KMeans(n_clusters=3)

# hacemos el entrenamiento del modelo, que sería
# explícitamente hacer los cálculos que require y guardar
# los clusters que se obtienen que corresponden a los centros
# de los grupos. 
k_means.fit(X_iris)


# el método labels me dice las etiquetas de los grupos
# que se le da a cada uno de los ejemplos. En este caso
# como se decidieron hacer 3 clusters, entonces las etiquetas
# son los valores 0, 1 y 2. 
display(k_means.labels_[::10])

# estos son los valores reales. 
display(y_iris[::10])

# es importante mencionar que las etiquetas no tiene porque ser iguales
# lo que importa es que los respectivos valores los 
# agrupa de una manera diferente en 3 grupos entre ellos
# como pasa con los datosd reales de Y. 


array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2], dtype=int32)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2])

## Vector quantization
Esta es una técnica de compresión que reemplaza un conjunto infinito o enorme de datos coninuos por un grupo pequeño y fijo de
vecotres representativos. 

¿Cómo funciona?

1. Creación del diccionario(codebook): Se analizan los datos originales y se agrupan mediante un algoritmo como k-means. El centroide de cada grupo se convierte en un punto representativo del diccionario. 

2. Asignación (Cuantización): Cada vector original x se compara con el diccionario y se reemplaza por el índice i del centroide más cerano. 

3. Comprensión: En lugar de guardar los vectores complejos originales, solo guardas la lista de índices y la tabla del diccionario. 

Esta es una gran teçnica en bases de datos vectoriale sy búsqueda en IA pues premite comprimir valores y búsquedas ultra rápidas. 



In [ ]:
#
# Vector quantization
# 
import scipy as sp

try:
    # importar imagenm de mapache
    face = sp.face(gray=True)
except AttributeError:
    from scipy import misc
    face = misc.face(gray=True)

# Transforma los datos a un array de (n_sample, n_feature)
X = face.reshape((-1, 1)) # esto en específico es para 
# transformar un arreglo unidimensionarl en una matriz 
# bidimensional con N filas y exactamente 1 columna. 
# el -1 representa las filas autmáticas tomadas
# como el número de elementos. Se usa básicamente
# para entregar los datos como un vector columna ya que esta 
# es la forma en que los métodos de sickit-learn reciben
# los datos. 

# creamos una instancia de k-means
k_means = cluster.KMeans(
    n_clusters=5, # 5 clusters
    n_init=1, # número de veces que el algoritmo corre con diferentes semillas para los centros
)

# entrenamiento del modelo.
k_means.fit(X)

# el método
values = k_means.cluster_centers_.squeeze()
labels = k_means.labels_
face_compressed = np.choose(labels, values)
face_compressed.shape = face.shape

ImportError: Missing optional dependency 'pooch' required for scipy.datasets module. Please use pip or conda to install 'pooch'.

## Agrupamiento jerárquico: Aglomerativo o divisivo
Es un método de aprendizaje no supervisado que ogarniza los datos en una estructura de forma de árbol llamada dendograma, mostrando cómo se agrupan los puntos a diferentes niveles de similitud. 

Estrategias de construcción: 

* Aglomerativo (Bottom-Up): Es el enfoque más utilizado. Comienza asumiendo que cada dato es su propio grupo. En cada paso, calcula las distancias y une los dos grupos más cercanos hasta que todos los puntos terminan en un único gran grupo.

* Divisivo (Top-Down): Funciona a la inversa. Parte de un solo grupo con todos los datos y lo va dividiendo recursivamente en subgrupos cada vez más pequeños.

Criterios de Enlace (Linkage)

Para decidir qué dos grupos deben unirse, el algoritmo necesita medir la distancia entre conjuntos de puntos. Los métodos más comunes son:

Single (Enlace simple): Mide la distancia entre los dos puntos más cercanos de cada grupo. Puede crear grupos "alargados" (efecto encadenamiento).

Complete (Enlace completo): Mide la distancia entre los dos puntos más lejanos de cada grupo. Tiende a crear grupos compactos y esféricos.

Average (Promedio): Mide la distancia promedio entre todos los pares de puntos de ambos grupos.

Ward: Minimiza la varianza total dentro de los grupos al unirlos. Es el criterio más robusto y utilizado en la práctica.

El Dendrograma y la elección de $K$A diferencia de $K$-Means, el agrupamiento jerárquico no requiere definir el número de grupos ($K$) antes de empezar.El resultado es el dendrograma: un diagrama donde la altura de las ramas representa la distancia a la que se unieron los grupos. Para definir el número final de clusters, simplemente realizas un "corte" horizontal a la altura deseada

Ventajas y Limitaciones

Ventajas: Muestra la jerarquía real de los datos y no requiere fijar $K$ de antemano.

Desventajas: Su complejidad computacional es alta ($\mathcal{O}(N^3)$ en implementaciones simples o $\mathcal{O}(N^2)$ optimizada), por lo que es inviable para conjuntos de datos masivos.

In [ ]:
import numpy as np
from scipy.ndimage import gaussian_filter
from skimage.data import coins # conjutno de imágenes de mones
#para agrupar con las similares. 

from skimage.transform import rescale

# 1. Cargar imagen base
imagen_base = coins()

# 2. Suavizar con filtro Gaussiano (sigma=2)
imagen_suavizada = gaussian_filter(imagen_base, sigma=2)

# 3. Reescalar al 20% con parámetros compatibles para versiones modernas
rescaled_coins = rescale(
    imagen_suavizada,
    scale=0.2,
    mode="reflect",
    anti_aliasing=False,
    channel_axis=None  # Desactiva búsqueda de canales de color en imágenes 2D
)

# 4. Transformar matriz (Alto, Ancho) a vector columna (N, 1)
# para tener un vector columna. 
X = np.reshape(rescaled_coins, (-1, 1))

print("Forma de la imagen reescalada:", rescaled_coins.shape)
print("Forma de la matriz X para ML:", X.shape)

Forma de la imagen reescalada: (61, 77)
Forma de la matriz X para ML: (4697, 1)


In [13]:
from sklearn.feature_extraction import grid_to_graph

connectivity = grid_to_graph(*rescaled_coins.shape)

# minuto 1:6:40

In [14]:
n_clusters = 27  # number of regions

from sklearn.cluster import AgglomerativeClustering

ward = AgglomerativeClustering(
    n_clusters=n_clusters,
    linkage="ward",
    connectivity=connectivity,
)
ward.fit(X)
label = np.reshape(ward.labels_, rescaled_coins.shape)
label[:10]

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,
         2,  2

In [ ]:
#
# Feature agglomeration
#
digits = datasets.load_digits()
images = digits.images
X = np.reshape(images, (len(images), -1))
connectivity = grid_to_graph(*images[0].shape)

agglo = cluster.FeatureAgglomeration(
    connectivity=connectivity,
    n_clusters=32,
)
agglo.fit(X)
X_reduced = agglo.transform(X)

X_approx = agglo.inverse_transform(X_reduced)
images_approx = np.reshape(X_approx, images.shape)